import { Blueprint } from './types';

export const blueprints: Blueprint[] = [
  {
    id: 'healthchat',
    name: 'HealthChat',
    description: 'Real-time Chain-of-Thought visualization from HealthChat',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 120, status: 'dormant', description: "User's healthcare question received" },
      { id: 'analyzing', label: 'Analyzing Query', type: 'process', icon: 'brain', x: 250, y: 120, status: 'dormant', description: 'Analyzing user intent and query complexity' },
      { id: 'augmenting', label: 'Context Augmentation', type: 'assembly', icon: 'zap', x: 450, y: 120, status: 'dormant', description: 'Augmenting context with conversation history' },
      { id: 'retrieving', label: 'Document Retrieval', type: 'retrieval', icon: 'database', x: 650, y: 120, status: 'dormant', description: 'Retrieving relevant healthcare documents' },
      { id: 'analyzing_document', label: 'Analyzing Documents', type: 'process', icon: 'file-text', x: 850, y: 120, status: 'dormant', description: 'Processing retrieved documents' },
      { id: 'checking', label: 'Input Guardrails', type: 'validate', icon: 'shield-check', x: 850, y: 320, status: 'dormant', description: 'Checking input for safety and policy violations' },
      { id: 'generating', label: 'Generating Response', type: 'execute', icon: 'cpu', x: 650, y: 320, status: 'dormant', description: 'LLM generating healthcare response' },
      { id: 'validating', label: 'Output Guardrails', type: 'validate', icon: 'check-circle', x: 450, y: 320, status: 'dormant', description: 'Validating response for safety and accuracy' },
      { id: 'output', label: 'Response Ready', type: 'output', icon: 'upload', x: 250, y: 320, status: 'dormant', description: 'Final response delivered to user' },
      { id: 'suggestions', label: 'Suggestions', type: 'validate', icon: 'lightbulb', x: 50, y: 320, status: 'dormant', description: 'Generating follow-up suggestions' },
    ],
    connections: [
      { from: 'intake', to: 'analyzing' },
      { from: 'analyzing', to: 'augmenting' },
      { from: 'augmenting', to: 'retrieving' },
      { from: 'retrieving', to: 'analyzing_document' },
      { from: 'analyzing_document', to: 'checking' },
      { from: 'checking', to: 'generating' },
      { from: 'generating', to: 'validating' },
      { from: 'validating', to: 'output' },
      { from: 'output', to: 'suggestions' },
    ],
    scenarios: [
      {
        id: 'healthcare',
        name: 'Healthcare',
        description: 'Real-time Chain-of-Thought from HealthChat',
        query: 'Waiting for real-time data from HealthChat...',
        activeNodes: [],
        events: [],
        chatMessages: [
          { 
            role: 'system', 
            content: 'Connected to HealthChat backend. Send a message in HealthChat to see real-time CoT animation.',
            timing: 0 
          },
        ],
      },
    ],
  },
  {
    id: 'llm-routing',
    name: 'LLM Routing',
    description: 'Intelligent routing of queries to optimal language models',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 250, status: 'dormant', description: "Receives the user's natural-language request. Starting point for the system's reasoning." },
      { id: 'preprocess', label: 'Preprocessing', type: 'process', icon: 'align-left', x: 200, y: 250, status: 'dormant', description: 'Cleans and normalizes the input query for analysis.' },
      { id: 'classify', label: 'Classifier', type: 'classify', icon: 'share-2', x: 350, y: 250, status: 'dormant', description: 'Determines the type and purpose of the query.' },
      { id: 'route', label: 'Router', type: 'route', icon: 'git-branch', x: 500, y: 250, status: 'dormant', description: 'Decides which specialized model should handle this task.' },
      { id: 'model-small', label: 'Small Model', type: 'model', icon: 'cpu', x: 650, y: 80, status: 'dormant', description: 'Efficient model for simple queries. Fast response with lower resource usage.' },
      { id: 'model-medium', label: 'Medium Model', type: 'model', icon: 'zap', x: 650, y: 250, status: 'dormant', description: 'Balanced model for marketing and creative tasks. Good performance with reasonable cost.' },
      { id: 'model-large', label: 'Large Model', type: 'model', icon: 'layers', x: 650, y: 440, status: 'dormant', description: 'Advanced model for complex technical queries. Maximum accuracy for challenging tasks.' },
      { id: 'execute', label: 'Execute', type: 'execute', icon: 'settings', x: 800, y: 250, status: 'dormant', description: 'Runs the selected model to produce a response.' },
      { id: 'validate', label: 'Validation', type: 'validate', icon: 'check-circle', x: 950, y: 250, status: 'dormant', description: 'Checks output quality and relevance before delivery.' },
      { id: 'output', label: 'Output', type: 'output', icon: 'upload', x: 1100, y: 250, status: 'dormant', description: 'Delivers the final response to the user.' },
    ],
    connections: [
      { from: 'intake', to: 'preprocess' },
      { from: 'preprocess', to: 'classify' },
      { from: 'classify', to: 'route' },
      { from: 'route', to: 'model-small' },
      { from: 'route', to: 'model-medium' },
      { from: 'route', to: 'model-large' },
      { from: 'model-small', to: 'execute' },
      { from: 'model-medium', to: 'execute' },
      { from: 'model-large', to: 'execute' },
      { from: 'execute', to: 'validate' },
      { from: 'validate', to: 'output' },
    ],
    scenarios: [
      {
        id: 'marketing-qa',
        name: 'Marketing Q&A',
        description: 'Generate a product promo for pediatrics',
        query: 'Generate a product promo for pediatrics',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-medium', 'execute', 'validate', 'output'],
        chosenPath: ['model-medium'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "Generate a product promo for pediatrics"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Marketing Q&A\' → Sent to Router',
            timing: 120,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Marketing Model based on complexity',
            timing: 150,
            status: 'completed',
            nodeIds: ['route', 'model-medium'],
          },
          {
            id: 'event-5',
            message: 'Retrieval step skipped—Not relevant for this scenario',
            timing: 160,
            status: 'skipped',
            nodeIds: [],
          },
          {
            id: 'event-6',
            message: 'Marketing Model is currently executing',
            timing: 200,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Model execution completed successfully',
            timing: 3200,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-8',
            message: 'Validating output quality and relevance',
            timing: 3300,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready for delivery',
            timing: 3400,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'Generate a product promo for pediatrics', timing: 0 },
          { role: 'system', content: 'Analyzing query type...', timing: 10 },
          { role: 'system', content: 'Classified as Marketing Q&A. Routing to specialized model.', timing: 120 },
          { role: 'system', content: 'Selected Marketing Model (Medium). Processing...', timing: 150 },
          { role: 'assistant', content: 'Introducing our pediatric care solution: Designed with children in mind, our innovative products combine safety, comfort, and effectiveness. Trusted by healthcare professionals worldwide, we help young patients receive the best care possible. Learn more about how we\'re making healthcare better for children.', timing: 3400 },
        ],
      },
      {
        id: 'technical-support',
        name: 'Technical Support',
        description: 'Complex technical query routing',
        query: 'Explain the implementation of transformer architecture in detail',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-large', 'execute', 'validate', 'output'],
        chosenPath: ['model-large'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "Explain the implementation of transformer architecture in detail"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Technical Support\' → Sent to Router',
            timing: 100,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Large Model for complex technical query',
            timing: 130,
            status: 'completed',
            nodeIds: ['route', 'model-large'],
          },
          {
            id: 'event-5',
            message: 'Large Model is currently executing',
            timing: 150,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed successfully',
            timing: 3500,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating technical accuracy',
            timing: 3600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output validated and ready',
            timing: 3700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'Explain the implementation of transformer architecture in detail', timing: 0 },
          { role: 'system', content: 'Analyzing query complexity...', timing: 10 },
          { role: 'system', content: 'High complexity detected. Routing to Large Model.', timing: 100 },
          { role: 'assistant', content: 'The Transformer architecture consists of an encoder-decoder structure with multi-head self-attention mechanisms. Key components include: 1) Positional encoding to capture sequence order, 2) Multi-head attention for parallel processing of different representation subspaces, 3) Feed-forward networks, 4) Layer normalization, and 5) Residual connections. The self-attention mechanism allows each position to attend to all positions in the previous layer, enabling better context understanding.', timing: 3700 },
        ],
      },
      {
        id: 'general-query',
        name: 'General Query',
        description: 'Simple query routing to efficient model',
        query: 'What is the weather like today?',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-small', 'execute', 'validate', 'output'],
        chosenPath: ['model-small'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is the weather like today?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 5,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'General Query\' → Sent to Router',
            timing: 50,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Small Model for efficiency',
            timing: 70,
            status: 'completed',
            nodeIds: ['route', 'model-small'],
          },
          {
            id: 'event-5',
            message: 'Small Model is currently executing',
            timing: 80,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed',
            timing: 1500,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating response',
            timing: 1600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output ready for delivery',
            timing: 1700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is the weather like today?', timing: 0 },
          { role: 'system', content: 'Simple query detected. Using efficient processing.', timing: 5 },
          { role: 'system', content: 'Routing to Small Model for fast response.', timing: 50 },
          { role: 'assistant', content: 'I don\'t have access to real-time weather data, but I can help you find weather information. You can check weather.com or your local weather service for current conditions in your area.', timing: 1700 },
        ],
      },
      {
        id: 'healthcare-query',
        name: 'Healthcare Query',
        description: 'Complex medical protocol routing',
        query: 'What are the HIPAA requirements for patient data retention in emergency departments?',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-large', 'execute', 'validate', 'output'],
        chosenPath: ['model-large'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What are the HIPAA requirements for patient data retention in emergency departments?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Healthcare Compliance\' → Sent to Router',
            timing: 110,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Large Model for healthcare compliance query',
            timing: 140,
            status: 'completed',
            nodeIds: ['route', 'model-large'],
          },
          {
            id: 'event-5',
            message: 'Large Model is currently executing',
            timing: 160,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed successfully',
            timing: 3600,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating healthcare compliance accuracy',
            timing: 3700,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output validated and ready',
            timing: 3800,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What are the HIPAA requirements for patient data retention in emergency departments?', timing: 0 },
          { role: 'system', content: 'Analyzing healthcare compliance query...', timing: 10 },
          { role: 'system', content: 'High complexity healthcare query detected. Routing to Large Model.', timing: 110 },
          { role: 'assistant', content: 'Under HIPAA regulations, emergency departments must retain patient records for a minimum of 6 years from the date of creation or last use, whichever is later. Key requirements include:\n\n1. **Medical Records**: Complete patient charts, treatment notes, and diagnostic results must be retained for at least 6 years\n2. **Minor Patients**: Records for patients under 18 must be kept until they reach age 21, or 6 years from last treatment, whichever is longer\n3. **State Requirements**: Some states (like California) require longer retention periods - verify local regulations\n4. **Electronic Records**: Must maintain same retention standards with proper backup and security measures\n5. **Disposal**: After retention period, records must be destroyed following HIPAA-compliant methods (shredding, electronic deletion)\n\nCanadian hospitals follow similar guidelines under PIPEDA, typically requiring 10-year retention for adult patient records.', timing: 3800 },
        ],
      },
    ],
  },
  {
    id: 'enterprise-rag',
    name: 'Enterprise RAG',
    description: 'Retrieval-Augmented Generation for enterprise knowledge',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 250, status: 'dormant', description: "Receives the user's question. Entry point for RAG pipeline." },
      { id: 'analyze', label: 'Query Analysis', type: 'process', icon: 'align-left', x: 200, y: 250, status: 'dormant', description: 'Analyzes query intent and extracts key terms for retrieval.' },
      { id: 'retrieval', label: 'Retrieval', type: 'retrieval', icon: 'database', x: 350, y: 250, status: 'dormant', description: 'Would fetch factual data or brand material for context. Not needed — this task uses creative knowledge only.' },
      { id: 'process-docs', label: 'Doc Processing', type: 'process', icon: 'file-text', x: 500, y: 250, status: 'dormant', description: 'Processes retrieved documents and extracts relevant information.' },
      { id: 'assembly', label: 'Context Assembly', type: 'assembly', icon: 'zap', x: 650, y: 250, status: 'dormant', description: 'Combines retrieved information into coherent context for the LLM.' },
      { id: 'generate', label: 'LLM Generation', type: 'execute', icon: 'cpu', x: 800, y: 250, status: 'dormant', description: 'Runs the selected model to produce a response based on retrieved context.' },
      { id: 'validate', label: 'Validation', type: 'validate', icon: 'check-circle', x: 950, y: 250, status: 'dormant', description: 'Validates response accuracy and completeness.' },
      { id: 'output', label: 'Output', type: 'output', icon: 'upload', x: 1100, y: 250, status: 'dormant', description: 'Delivers the final answer to the user.' },
    ],
    connections: [
      { from: 'intake', to: 'analyze' },
      { from: 'analyze', to: 'retrieval' },
      { from: 'retrieval', to: 'process-docs' },
      { from: 'process-docs', to: 'assembly' },
      { from: 'assembly', to: 'generate' },
      { from: 'generate', to: 'validate' },
      { from: 'validate', to: 'output' },
    ],
    scenarios: [
      {
        id: 'product-docs',
        name: 'Product Documentation',
        description: 'Search product documentation for answers',
        query: 'How do I configure SSL certificates in our platform?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "How do I configure SSL certificates in our platform?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query intent and extracting key terms',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving relevant documents from knowledge base',
            timing: 50,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 3 relevant documents found',
            timing: 200,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling context from retrieved documents',
            timing: 250,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'LLM generating response based on context',
            timing: 300,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Response generation completed',
            timing: 3000,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating response accuracy',
            timing: 3100,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3200,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'How do I configure SSL certificates in our platform?', timing: 0 },
          { role: 'system', content: 'Searching knowledge base...', timing: 10 },
          { role: 'system', content: 'Found 3 relevant documents. Processing...', timing: 200 },
          { role: 'assistant', content: 'To configure SSL certificates in the platform:\n\n1. Navigate to Settings > Security > SSL Certificates\n2. Click "Add New Certificate"\n3. Upload your certificate file (.crt) and private key (.key)\n4. Enter the domain name\n5. Click "Activate" to enable\n\nThe certificate will be validated and applied within 5 minutes. For wildcard certificates, ensure your domain starts with *.', timing: 3200 },
        ],
      },
      {
        id: 'policy-inquiry',
        name: 'Policy Inquiry',
        description: 'Search company policies',
        query: 'What is our remote work policy?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is our remote work policy?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query intent',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving policy documents',
            timing: 40,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing HR policy documents',
            timing: 150,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling policy context',
            timing: 180,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating policy summary',
            timing: 220,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Policy summary generated',
            timing: 2500,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating policy information',
            timing: 2600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output ready for delivery',
            timing: 2700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is our remote work policy?', timing: 0 },
          { role: 'system', content: 'Searching HR policies...', timing: 10 },
          { role: 'system', content: 'Found relevant policy documents. Extracting information...', timing: 150 },
          { role: 'assistant', content: 'Our remote work policy allows employees to work remotely up to 3 days per week with manager approval. Key points:\n\n• Must maintain regular working hours\n• Required to attend in-person meetings when scheduled\n• Home office must meet security requirements\n• Equipment provided by company\n• VPN access required for all remote connections\n\nFor full-time remote positions, separate approval is needed from HR.', timing: 2700 },
        ],
      },
      {
        id: 'knowledge-base',
        name: 'Knowledge Base Query',
        description: 'Multi-document knowledge retrieval',
        query: 'What are the system requirements for deployment?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What are the system requirements for deployment?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query and extracting keywords',
            timing: 8,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving deployment documentation',
            timing: 45,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 5 technical documents',
            timing: 180,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling comprehensive context',
            timing: 230,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating detailed response',
            timing: 270,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Response generation completed',
            timing: 2800,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating technical specifications',
            timing: 2900,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3000,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What are the system requirements for deployment?', timing: 0 },
          { role: 'system', content: 'Searching deployment documentation...', timing: 8 },
          { role: 'system', content: 'Retrieving technical specifications from 5 documents...', timing: 180 },
          { role: 'assistant', content: 'System requirements for deployment:\n\n**Hardware:**\n• CPU: 8+ cores (16+ recommended)\n• RAM: 32GB minimum (64GB for production)\n• Storage: 500GB SSD\n\n**Software:**\n• OS: Ubuntu 20.04 LTS or RHEL 8+\n• Docker 24.0+\n• Kubernetes 1.28+\n• PostgreSQL 14+\n\n**Network:**\n• 1Gbps connection\n• Static IP address\n• Ports 80, 443, 8080 open', timing: 3000 },
        ],
      },
      {
        id: 'healthcare-protocol',
        name: 'Healthcare Protocol',
        description: 'Hospital clinical guidelines retrieval',
        query: 'What is the triage protocol for chest pain patients in the emergency department?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is the triage protocol for chest pain patients in the emergency department?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing clinical query intent',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving clinical protocols from medical database',
            timing: 50,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 4 clinical guideline documents',
            timing: 190,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling protocol context from guidelines',
            timing: 240,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating clinical protocol summary',
            timing: 280,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Protocol summary generated',
            timing: 2900,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating clinical accuracy',
            timing: 3000,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3100,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is the triage protocol for chest pain patients in the emergency department?', timing: 0 },
          { role: 'system', content: 'Searching clinical protocols database...', timing: 10 },
          { role: 'system', content: 'Found 4 relevant clinical guidelines. Processing...', timing: 190 },
          { role: 'assistant', content: 'Emergency Department Triage Protocol for Chest Pain (Based on AHA/ACC Guidelines):\n\n**Immediate Assessment (ESI Level 1-2):**\n• Obtain vital signs: BP, HR, O2 saturation, temperature\n• 12-lead ECG within 10 minutes of arrival\n• Establish IV access\n• Continuous cardiac monitoring\n\n**Risk Stratification:**\n• **High Risk** - STEMI, unstable angina, severe dyspnea → Immediate physician evaluation\n• **Moderate Risk** - Atypical symptoms, risk factors present → Observation unit, troponin serial testing\n• **Low Risk** - No cardiac risk factors, reproducible chest wall pain → Standard evaluation\n\n**Initial Management:**\n• Aspirin 325mg (if no contraindications)\n• Nitroglycerin for ongoing pain\n• Oxygen if SpO2 <94%\n• Serial troponin at 0, 3, and 6 hours\n\n**Disposition:**\n• Cardiology consult for positive findings\n• Transfer to CCU/Cath Lab if STEMI confirmed\n• Observation unit for moderate risk\n• Discharge with cardiology follow-up if negative workup\n\nFollow hospital-specific protocols and contact on-call cardiology for consultation.', timing: 3100 },
        ],
      },
    ],
  },
];

export function getBlueprintById(id: string): Blueprint | undefined {
  return blueprints.find(bp => bp.id === id);
}

export function getScenarioById(blueprintId: string, scenarioId: string) {
  const blueprint = getBlueprintById(blueprintId);
  return blueprint?.scenarios.find(s => s.id === scenarioId);
}

