import { Blueprint } from './types';

export const blueprints: Blueprint[] = [
  {
    id: 'healthchat',
    name: 'HealthChat',
    description: 'Real-time Chain-of-Thought visualization from HealthChat',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 120, status: 'dormant', description: "User's healthcare question received" },
      { id: 'analyzing', label: 'Analyzing Query', type: 'process', icon: 'brain', x: 250, y: 120, status: 'dormant', description: 'Analyzing user intent and query complexity' },
      { id: 'augmenting', label: 'Context Augmentation', type: 'assembly', icon: 'zap', x: 450, y: 120, status: 'dormant', description: 'Augmenting context with conversation history' },
      { id: 'retrieving', label: 'Document Retrieval', type: 'retrieval', icon: 'database', x: 650, y: 120, status: 'dormant', description: 'Retrieving relevant healthcare documents' },
      { id: 'analyzing_document', label: 'Analyzing Documents', type: 'process', icon: 'file-text', x: 850, y: 120, status: 'dormant', description: 'Processing retrieved documents' },
      { id: 'checking', label: 'Input Guardrails', type: 'validate', icon: 'shield-check', x: 850, y: 320, status: 'dormant', description: 'Checking input for safety and policy violations' },
      { id: 'generating', label: 'Generating Response', type: 'execute', icon: 'cpu', x: 650, y: 320, status: 'dormant', description: 'LLM generating healthcare response' },
      { id: 'validating', label: 'Output Guardrails', type: 'validate', icon: 'check-circle', x: 450, y: 320, status: 'dormant', description: 'Validating response for safety and accuracy' },
      { id: 'output', label: 'Response Ready', type: 'output', icon: 'upload', x: 250, y: 320, status: 'dormant', description: 'Final response delivered to user' },
      { id: 'suggestions', label: 'Suggestions', type: 'validate', icon: 'lightbulb', x: 50, y: 320, status: 'dormant', description: 'Generating follow-up suggestions' },
    ],
    connections: [
      { from: 'intake', to: 'analyzing' },
      { from: 'analyzing', to: 'augmenting' },
      { from: 'augmenting', to: 'retrieving' },
      { from: 'retrieving', to: 'analyzing_document' },
      { from: 'analyzing_document', to: 'checking' },
      { from: 'checking', to: 'generating' },
      { from: 'generating', to: 'validating' },
      { from: 'validating', to: 'output' },
      { from: 'output', to: 'suggestions' },
    ],
    scenarios: [
      {
        id: 'healthcare',
        name: 'Healthcare',
        description: 'Real-time Chain-of-Thought from HealthChat',
        query: 'Waiting for real-time data from HealthChat...',
        activeNodes: [],
        events: [],
        chatMessages: [
          {
            role: 'system',
            content: 'Connected to HealthChat backend. Send a message in HealthChat to see real-time CoT animation.',
            timing: 0
          },
        ],
      },
    ],
  },
  {
    id: 'nvidia-rag',
    name: 'NVIDIA RAG',
    description: 'Real-time NVIDIA Retrieval-Augmented Generation pipeline visualization',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 250, status: 'dormant', description: "User's query received and preprocessed" },
      { id: 'embedding', label: 'NeMo Embeddings', type: 'process', icon: 'brain', x: 200, y: 250, status: 'dormant', description: 'Converting query to vector embeddings using NeMo Retriever' },
      { id: 'retrieval', label: 'Vector Search', type: 'retrieval', icon: 'database', x: 350, y: 250, status: 'dormant', description: 'Searching vector database for relevant documents' },
      { id: 'reranking', label: 'Reranking', type: 'process', icon: 'arrows-up-down', x: 500, y: 250, status: 'dormant', description: 'Cross-encoder reranking for better relevance' },
      { id: 'context_assembly', label: 'Context Assembly', type: 'assembly', icon: 'zap', x: 650, y: 250, status: 'dormant', description: 'Assembling retrieved context for generation' },
      { id: 'generation', label: 'NIM Generation', type: 'execute', icon: 'cpu', x: 800, y: 250, status: 'dormant', description: 'NVIDIA NIM LLM generating response with context' },
      { id: 'output', label: 'Response Ready', type: 'output', icon: 'upload', x: 950, y: 250, status: 'dormant', description: 'Final response with citations delivered' },
    ],
    connections: [
      { from: 'intake', to: 'embedding' },
      { from: 'embedding', to: 'retrieval' },
      { from: 'retrieval', to: 'reranking' },
      { from: 'reranking', to: 'context_assembly' },
      { from: 'context_assembly', to: 'generation' },
      { from: 'generation', to: 'output' },
    ],
    scenarios: [
      {
        id: 'realtime',
        name: 'Real-time RAG',
        description: 'Live NVIDIA RAG pipeline execution',
        query: 'Waiting for RAG query...',
        activeNodes: [],
        events: [],
        chatMessages: [
          {
            role: 'system',
            content: 'Ready to process RAG queries. Send a question to see the NVIDIA RAG pipeline in action.',
            timing: 0
          },
        ],
      },
      {
        id: 'document-qa',
        name: 'Document Q&A',
        description: 'Question answering from technical documentation',
        query: 'What are the system requirements for deploying NVIDIA NIM?',
        activeNodes: ['intake', 'embedding', 'retrieval', 'reranking', 'context_assembly', 'generation', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What are the system requirements for deploying NVIDIA NIM?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Generating query embeddings with NeMo Retriever',
            timing: 10,
            status: 'completed',
            nodeIds: ['embedding'],
          },
          {
            id: 'event-3',
            message: 'Vector search: Retrieved 12 candidate documents',
            timing: 55,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Reranking candidates with cross-encoder (top 5 selected)',
            timing: 175,
            status: 'completed',
            nodeIds: ['reranking'],
          },
          {
            id: 'event-5',
            message: 'Assembling context from top-ranked documents',
            timing: 260,
            status: 'completed',
            nodeIds: ['context_assembly'],
          },
          {
            id: 'event-6',
            message: 'NIM generating response with retrieved context',
            timing: 290,
            status: 'running',
            nodeIds: ['generation'],
          },
          {
            id: 'event-7',
            message: 'Response generation completed',
            timing: 3290,
            status: 'completed',
            nodeIds: ['generation'],
          },
          {
            id: 'event-8',
            message: 'Response ready with source citations',
            timing: 3320,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What are the system requirements for deploying NVIDIA NIM?', timing: 0 },
          { role: 'system', content: 'Generating embeddings and searching documentation...', timing: 10 },
          { role: 'system', content: 'Retrieved 12 documents. Reranking for relevance...', timing: 55 },
          { role: 'system', content: 'Top 5 documents selected. Generating response...', timing: 260 },
          { role: 'assistant', content: 'Based on the NVIDIA NIM deployment documentation:\n\n**System Requirements:**\n\n**Hardware:**\n• GPU: NVIDIA A100, H100, or L40S (minimum 40GB VRAM)\n• CPU: 32+ cores recommended\n• RAM: 128GB minimum (256GB for production)\n• Storage: 1TB NVMe SSD for model cache\n\n**Software:**\n• OS: Ubuntu 22.04 LTS or RHEL 9\n• Docker 24.0+ with NVIDIA Container Toolkit\n• Kubernetes 1.28+ (for orchestration)\n• NVIDIA Driver 535+\n\n**Network:**\n• 10Gbps connection recommended\n• Ports 8000 (inference), 8001 (metrics)\n\n*Sources: nim-deployment-guide.pdf, system-requirements.pdf*', timing: 3320 },
        ],
      },
      {
        id: 'policy-compliance',
        name: 'Policy & Compliance',
        description: 'Compliance query with document retrieval',
        query: 'What is our data retention policy for customer PII?',
        activeNodes: ['intake', 'embedding', 'retrieval', 'reranking', 'context_assembly', 'generation', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is our data retention policy for customer PII?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Generating embeddings for compliance query',
            timing: 10,
            status: 'completed',
            nodeIds: ['embedding'],
          },
          {
            id: 'event-3',
            message: 'Searching policy database: 8 documents found',
            timing: 48,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Reranking compliance documents',
            timing: 145,
            status: 'completed',
            nodeIds: ['reranking'],
          },
          {
            id: 'event-5',
            message: 'Assembling policy context',
            timing: 230,
            status: 'completed',
            nodeIds: ['context_assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating response with compliance context',
            timing: 260,
            status: 'running',
            nodeIds: ['generation'],
          },
          {
            id: 'event-7',
            message: 'Response generated',
            timing: 2760,
            status: 'completed',
            nodeIds: ['generation'],
          },
          {
            id: 'event-8',
            message: 'Response delivered with policy citations',
            timing: 2790,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is our data retention policy for customer PII?', timing: 0 },
          { role: 'system', content: 'Compliance query detected. Searching policy database...', timing: 10 },
          { role: 'system', content: 'Found 8 relevant policy documents. Processing and generating response...', timing: 48 },
          { role: 'assistant', content: 'According to our Data Governance Policy (updated Q2 2025):\n\n**Customer PII Retention:**\n\n• **Active Customers**: Retained for duration of relationship + 90 days\n• **Inactive Customers**: 7 years from last transaction (regulatory requirement)\n• **Marketing Data**: 3 years with opt-out honored immediately\n• **Support Logs**: 2 years (PII redacted after 90 days)\n\n**Deletion Process:**\n• Automated deletion runs monthly\n• Manual requests processed within 30 days\n• Audit logs maintained for 10 years (no PII)\n\n**Compliance:** GDPR, CCPA, HIPAA where applicable\n\n*Sources: data-governance-policy-2025.pdf, retention-schedule.pdf*', timing: 2790 },
        ],
      },
    ],
  },
  {
    id: 'llm-routing',
    name: 'LLM Routing',
    description: 'Intelligent routing of queries to optimal language models',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 250, status: 'dormant', description: "Receives the user's natural-language request. Starting point for the system's reasoning." },
      { id: 'preprocess', label: 'Preprocessing', type: 'process', icon: 'align-left', x: 200, y: 250, status: 'dormant', description: 'Cleans and normalizes the input query for analysis.' },
      { id: 'classify', label: 'Classifier', type: 'classify', icon: 'share-2', x: 350, y: 250, status: 'dormant', description: 'Determines the type and purpose of the query.' },
      { id: 'route', label: 'Router', type: 'route', icon: 'git-branch', x: 500, y: 250, status: 'dormant', description: 'Decides which specialized model should handle this task.' },
      { id: 'model-small', label: 'Small Model', type: 'model', icon: 'cpu', x: 650, y: 80, status: 'dormant', description: 'Efficient model for simple queries. Fast response with lower resource usage.' },
      { id: 'model-medium', label: 'Medium Model', type: 'model', icon: 'zap', x: 650, y: 250, status: 'dormant', description: 'Balanced model for marketing and creative tasks. Good performance with reasonable cost.' },
      { id: 'model-large', label: 'Large Model', type: 'model', icon: 'layers', x: 650, y: 440, status: 'dormant', description: 'Advanced model for complex technical queries. Maximum accuracy for challenging tasks.' },
      { id: 'execute', label: 'Execute', type: 'execute', icon: 'settings', x: 800, y: 250, status: 'dormant', description: 'Runs the selected model to produce a response.' },
      { id: 'validate', label: 'Validation', type: 'validate', icon: 'check-circle', x: 950, y: 250, status: 'dormant', description: 'Checks output quality and relevance before delivery.' },
      { id: 'output', label: 'Output', type: 'output', icon: 'upload', x: 1100, y: 250, status: 'dormant', description: 'Delivers the final response to the user.' },
    ],
    connections: [
      { from: 'intake', to: 'preprocess' },
      { from: 'preprocess', to: 'classify' },
      { from: 'classify', to: 'route' },
      { from: 'route', to: 'model-small' },
      { from: 'route', to: 'model-medium' },
      { from: 'route', to: 'model-large' },
      { from: 'model-small', to: 'execute' },
      { from: 'model-medium', to: 'execute' },
      { from: 'model-large', to: 'execute' },
      { from: 'execute', to: 'validate' },
      { from: 'validate', to: 'output' },
    ],
    scenarios: [
      {
        id: 'marketing-qa',
        name: 'Marketing Q&A',
        description: 'Generate a product promo for pediatrics',
        query: 'Generate a product promo for pediatrics',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-medium', 'execute', 'validate', 'output'],
        chosenPath: ['model-medium'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "Generate a product promo for pediatrics"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Marketing Q&A\' → Sent to Router',
            timing: 120,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Marketing Model based on complexity',
            timing: 150,
            status: 'completed',
            nodeIds: ['route', 'model-medium'],
          },
          {
            id: 'event-5',
            message: 'Retrieval step skipped—Not relevant for this scenario',
            timing: 160,
            status: 'skipped',
            nodeIds: [],
          },
          {
            id: 'event-6',
            message: 'Marketing Model is currently executing',
            timing: 200,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Model execution completed successfully',
            timing: 3200,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-8',
            message: 'Validating output quality and relevance',
            timing: 3300,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready for delivery',
            timing: 3400,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'Generate a product promo for pediatrics', timing: 0 },
          { role: 'system', content: 'Analyzing query type...', timing: 10 },
          { role: 'system', content: 'Classified as Marketing Q&A. Routing to specialized model.', timing: 120 },
          { role: 'system', content: 'Selected Marketing Model (Medium). Processing...', timing: 150 },
          { role: 'assistant', content: 'Introducing our pediatric care solution: Designed with children in mind, our innovative products combine safety, comfort, and effectiveness. Trusted by healthcare professionals worldwide, we help young patients receive the best care possible. Learn more about how we\'re making healthcare better for children.', timing: 3400 },
        ],
      },
      {
        id: 'technical-support',
        name: 'Technical Support',
        description: 'Complex technical query routing',
        query: 'Explain the implementation of transformer architecture in detail',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-large', 'execute', 'validate', 'output'],
        chosenPath: ['model-large'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "Explain the implementation of transformer architecture in detail"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Technical Support\' → Sent to Router',
            timing: 100,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Large Model for complex technical query',
            timing: 130,
            status: 'completed',
            nodeIds: ['route', 'model-large'],
          },
          {
            id: 'event-5',
            message: 'Large Model is currently executing',
            timing: 150,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed successfully',
            timing: 3500,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating technical accuracy',
            timing: 3600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output validated and ready',
            timing: 3700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'Explain the implementation of transformer architecture in detail', timing: 0 },
          { role: 'system', content: 'Analyzing query complexity...', timing: 10 },
          { role: 'system', content: 'High complexity detected. Routing to Large Model.', timing: 100 },
          { role: 'assistant', content: 'The Transformer architecture consists of an encoder-decoder structure with multi-head self-attention mechanisms. Key components include: 1) Positional encoding to capture sequence order, 2) Multi-head attention for parallel processing of different representation subspaces, 3) Feed-forward networks, 4) Layer normalization, and 5) Residual connections. The self-attention mechanism allows each position to attend to all positions in the previous layer, enabling better context understanding.', timing: 3700 },
        ],
      },
      {
        id: 'general-query',
        name: 'General Query',
        description: 'Simple query routing to efficient model',
        query: 'What is the weather like today?',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-small', 'execute', 'validate', 'output'],
        chosenPath: ['model-small'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is the weather like today?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 5,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'General Query\' → Sent to Router',
            timing: 50,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Small Model for efficiency',
            timing: 70,
            status: 'completed',
            nodeIds: ['route', 'model-small'],
          },
          {
            id: 'event-5',
            message: 'Small Model is currently executing',
            timing: 80,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed',
            timing: 1500,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating response',
            timing: 1600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output ready for delivery',
            timing: 1700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is the weather like today?', timing: 0 },
          { role: 'system', content: 'Simple query detected. Using efficient processing.', timing: 5 },
          { role: 'system', content: 'Routing to Small Model for fast response.', timing: 50 },
          { role: 'assistant', content: 'I don\'t have access to real-time weather data, but I can help you find weather information. You can check weather.com or your local weather service for current conditions in your area.', timing: 1700 },
        ],
      },
      {
        id: 'healthcare-query',
        name: 'Healthcare Query',
        description: 'Complex medical protocol routing',
        query: 'What are the HIPAA requirements for patient data retention in emergency departments?',
        activeNodes: ['intake', 'preprocess', 'classify', 'route', 'model-large', 'execute', 'validate', 'output'],
        chosenPath: ['model-large'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What are the HIPAA requirements for patient data retention in emergency departments?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Query sent to Classifier for analysis',
            timing: 10,
            status: 'completed',
            nodeIds: ['preprocess', 'classify'],
          },
          {
            id: 'event-3',
            message: 'Classified as \'Healthcare Compliance\' → Sent to Router',
            timing: 110,
            status: 'completed',
            nodeIds: ['classify', 'route'],
          },
          {
            id: 'event-4',
            message: 'Router selected Large Model for healthcare compliance query',
            timing: 140,
            status: 'completed',
            nodeIds: ['route', 'model-large'],
          },
          {
            id: 'event-5',
            message: 'Large Model is currently executing',
            timing: 160,
            status: 'running',
            nodeIds: ['execute'],
          },
          {
            id: 'event-6',
            message: 'Model execution completed successfully',
            timing: 3600,
            status: 'completed',
            nodeIds: ['execute'],
          },
          {
            id: 'event-7',
            message: 'Validating healthcare compliance accuracy',
            timing: 3700,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-8',
            message: 'Output validated and ready',
            timing: 3800,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What are the HIPAA requirements for patient data retention in emergency departments?', timing: 0 },
          { role: 'system', content: 'Analyzing healthcare compliance query...', timing: 10 },
          { role: 'system', content: 'High complexity healthcare query detected. Routing to Large Model.', timing: 110 },
          { role: 'assistant', content: 'Under HIPAA regulations, emergency departments must retain patient records for a minimum of 6 years from the date of creation or last use, whichever is later. Key requirements include:\n\n1. **Medical Records**: Complete patient charts, treatment notes, and diagnostic results must be retained for at least 6 years\n2. **Minor Patients**: Records for patients under 18 must be kept until they reach age 21, or 6 years from last treatment, whichever is longer\n3. **State Requirements**: Some states (like California) require longer retention periods - verify local regulations\n4. **Electronic Records**: Must maintain same retention standards with proper backup and security measures\n5. **Disposal**: After retention period, records must be destroyed following HIPAA-compliant methods (shredding, electronic deletion)\n\nCanadian hospitals follow similar guidelines under PIPEDA, typically requiring 10-year retention for adult patient records.', timing: 3800 },
        ],
      },
    ],
  },
  {
    id: 'enterprise-rag',
    name: 'Enterprise RAG',
    description: 'Retrieval-Augmented Generation for enterprise knowledge',
    nodes: [
      { id: 'intake', label: 'Query Intake', type: 'intake', icon: 'download', x: 50, y: 250, status: 'dormant', description: "Receives the user's question. Entry point for RAG pipeline." },
      { id: 'analyze', label: 'Query Analysis', type: 'process', icon: 'align-left', x: 200, y: 250, status: 'dormant', description: 'Analyzes query intent and extracts key terms for retrieval.' },
      { id: 'retrieval', label: 'Retrieval', type: 'retrieval', icon: 'database', x: 350, y: 250, status: 'dormant', description: 'Would fetch factual data or brand material for context. Not needed — this task uses creative knowledge only.' },
      { id: 'process-docs', label: 'Doc Processing', type: 'process', icon: 'file-text', x: 500, y: 250, status: 'dormant', description: 'Processes retrieved documents and extracts relevant information.' },
      { id: 'assembly', label: 'Context Assembly', type: 'assembly', icon: 'zap', x: 650, y: 250, status: 'dormant', description: 'Combines retrieved information into coherent context for the LLM.' },
      { id: 'generate', label: 'LLM Generation', type: 'execute', icon: 'cpu', x: 800, y: 250, status: 'dormant', description: 'Runs the selected model to produce a response based on retrieved context.' },
      { id: 'validate', label: 'Validation', type: 'validate', icon: 'check-circle', x: 950, y: 250, status: 'dormant', description: 'Validates response accuracy and completeness.' },
      { id: 'output', label: 'Output', type: 'output', icon: 'upload', x: 1100, y: 250, status: 'dormant', description: 'Delivers the final answer to the user.' },
    ],
    connections: [
      { from: 'intake', to: 'analyze' },
      { from: 'analyze', to: 'retrieval' },
      { from: 'retrieval', to: 'process-docs' },
      { from: 'process-docs', to: 'assembly' },
      { from: 'assembly', to: 'generate' },
      { from: 'generate', to: 'validate' },
      { from: 'validate', to: 'output' },
    ],
    scenarios: [
      {
        id: 'product-docs',
        name: 'Product Documentation',
        description: 'Search product documentation for answers',
        query: 'How do I configure SSL certificates in our platform?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "How do I configure SSL certificates in our platform?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query intent and extracting key terms',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving relevant documents from knowledge base',
            timing: 50,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 3 relevant documents found',
            timing: 200,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling context from retrieved documents',
            timing: 250,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'LLM generating response based on context',
            timing: 300,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Response generation completed',
            timing: 3000,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating response accuracy',
            timing: 3100,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3200,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'How do I configure SSL certificates in our platform?', timing: 0 },
          { role: 'system', content: 'Searching knowledge base...', timing: 10 },
          { role: 'system', content: 'Found 3 relevant documents. Processing...', timing: 200 },
          { role: 'assistant', content: 'To configure SSL certificates in the platform:\n\n1. Navigate to Settings > Security > SSL Certificates\n2. Click "Add New Certificate"\n3. Upload your certificate file (.crt) and private key (.key)\n4. Enter the domain name\n5. Click "Activate" to enable\n\nThe certificate will be validated and applied within 5 minutes. For wildcard certificates, ensure your domain starts with *.', timing: 3200 },
        ],
      },
      {
        id: 'policy-inquiry',
        name: 'Policy Inquiry',
        description: 'Search company policies',
        query: 'What is our remote work policy?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is our remote work policy?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query intent',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving policy documents',
            timing: 40,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing HR policy documents',
            timing: 150,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling policy context',
            timing: 180,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating policy summary',
            timing: 220,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Policy summary generated',
            timing: 2500,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating policy information',
            timing: 2600,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output ready for delivery',
            timing: 2700,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is our remote work policy?', timing: 0 },
          { role: 'system', content: 'Searching HR policies...', timing: 10 },
          { role: 'system', content: 'Found relevant policy documents. Extracting information...', timing: 150 },
          { role: 'assistant', content: 'Our remote work policy allows employees to work remotely up to 3 days per week with manager approval. Key points:\n\n• Must maintain regular working hours\n• Required to attend in-person meetings when scheduled\n• Home office must meet security requirements\n• Equipment provided by company\n• VPN access required for all remote connections\n\nFor full-time remote positions, separate approval is needed from HR.', timing: 2700 },
        ],
      },
      {
        id: 'knowledge-base',
        name: 'Knowledge Base Query',
        description: 'Multi-document knowledge retrieval',
        query: 'What are the system requirements for deployment?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What are the system requirements for deployment?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing query and extracting keywords',
            timing: 8,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving deployment documentation',
            timing: 45,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 5 technical documents',
            timing: 180,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling comprehensive context',
            timing: 230,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating detailed response',
            timing: 270,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Response generation completed',
            timing: 2800,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating technical specifications',
            timing: 2900,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3000,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What are the system requirements for deployment?', timing: 0 },
          { role: 'system', content: 'Searching deployment documentation...', timing: 8 },
          { role: 'system', content: 'Retrieving technical specifications from 5 documents...', timing: 180 },
          { role: 'assistant', content: 'System requirements for deployment:\n\n**Hardware:**\n• CPU: 8+ cores (16+ recommended)\n• RAM: 32GB minimum (64GB for production)\n• Storage: 500GB SSD\n\n**Software:**\n• OS: Ubuntu 20.04 LTS or RHEL 8+\n• Docker 24.0+\n• Kubernetes 1.28+\n• PostgreSQL 14+\n\n**Network:**\n• 1Gbps connection\n• Static IP address\n• Ports 80, 443, 8080 open', timing: 3000 },
        ],
      },
      {
        id: 'healthcare-protocol',
        name: 'Healthcare Protocol',
        description: 'Hospital clinical guidelines retrieval',
        query: 'What is the triage protocol for chest pain patients in the emergency department?',
        activeNodes: ['intake', 'analyze', 'retrieval', 'process-docs', 'assembly', 'generate', 'validate', 'output'],
        events: [
          {
            id: 'event-1',
            message: 'Query received: "What is the triage protocol for chest pain patients in the emergency department?"',
            timing: 0,
            status: 'completed',
            nodeIds: ['intake'],
          },
          {
            id: 'event-2',
            message: 'Analyzing clinical query intent',
            timing: 10,
            status: 'completed',
            nodeIds: ['analyze'],
          },
          {
            id: 'event-3',
            message: 'Retrieving clinical protocols from medical database',
            timing: 50,
            status: 'completed',
            nodeIds: ['retrieval'],
          },
          {
            id: 'event-4',
            message: 'Processing 4 clinical guideline documents',
            timing: 190,
            status: 'running',
            nodeIds: ['process-docs'],
          },
          {
            id: 'event-5',
            message: 'Assembling protocol context from guidelines',
            timing: 240,
            status: 'completed',
            nodeIds: ['assembly'],
          },
          {
            id: 'event-6',
            message: 'Generating clinical protocol summary',
            timing: 280,
            status: 'running',
            nodeIds: ['generate'],
          },
          {
            id: 'event-7',
            message: 'Protocol summary generated',
            timing: 2900,
            status: 'completed',
            nodeIds: ['generate'],
          },
          {
            id: 'event-8',
            message: 'Validating clinical accuracy',
            timing: 3000,
            status: 'completed',
            nodeIds: ['validate'],
          },
          {
            id: 'event-9',
            message: 'Output validated and ready',
            timing: 3100,
            status: 'completed',
            nodeIds: ['output'],
          },
        ],
        chatMessages: [
          { role: 'user', content: 'What is the triage protocol for chest pain patients in the emergency department?', timing: 0 },
          { role: 'system', content: 'Searching clinical protocols database...', timing: 10 },
          { role: 'system', content: 'Found 4 relevant clinical guidelines. Processing...', timing: 190 },
          { role: 'assistant', content: 'Emergency Department Triage Protocol for Chest Pain (Based on AHA/ACC Guidelines):\n\n**Immediate Assessment (ESI Level 1-2):**\n• Obtain vital signs: BP, HR, O2 saturation, temperature\n• 12-lead ECG within 10 minutes of arrival\n• Establish IV access\n• Continuous cardiac monitoring\n\n**Risk Stratification:**\n• **High Risk** - STEMI, unstable angina, severe dyspnea → Immediate physician evaluation\n• **Moderate Risk** - Atypical symptoms, risk factors present → Observation unit, troponin serial testing\n• **Low Risk** - No cardiac risk factors, reproducible chest wall pain → Standard evaluation\n\n**Initial Management:**\n• Aspirin 325mg (if no contraindications)\n• Nitroglycerin for ongoing pain\n• Oxygen if SpO2 <94%\n• Serial troponin at 0, 3, and 6 hours\n\n**Disposition:**\n• Cardiology consult for positive findings\n• Transfer to CCU/Cath Lab if STEMI confirmed\n• Observation unit for moderate risk\n• Discharge with cardiology follow-up if negative workup\n\nFollow hospital-specific protocols and contact on-call cardiology for consultation.', timing: 3100 },
        ],
      },
    ],
  },
  {
    id: 'meta-orchestrator',
    name: 'Meta-Orchestrator',
    description: 'Unified Enterprise AI Orchestration — NeMo Agent Toolkit Meta-Orchestrator',
    nodes: [
      // Layer 1 — HelpBot UI (y: 30)
      { id: 'helpbot-chat', label: 'HelpBot Chat', type: 'helpbot', icon: 'message-square', x: 50, y: 30, layer: 1, status: 'dormant', description: 'Single conversational entry point. User types natural-language requests here.' },
      { id: 'helpbot-todo', label: 'My To-Do', type: 'helpbot', icon: 'list-todo', x: 230, y: 30, layer: 1, status: 'dormant', description: 'Aggregated tasks from all connected platforms (Jira, ServiceNow, M365).' },
      { id: 'helpbot-approvals', label: 'My Approvals', type: 'helpbot', icon: 'shield-check', x: 410, y: 30, layer: 1, status: 'dormant', description: 'Pending human-in-the-loop approval actions queued by the orchestrator.' },
      { id: 'helpbot-updates', label: 'IT Updates', type: 'helpbot', icon: 'bell', x: 590, y: 30, layer: 1, status: 'dormant', description: 'Real-time incident and change notifications from ServiceNow and M365.' },
      { id: 'helpbot-vendor', label: 'Vendor Tasks', type: 'helpbot', icon: 'clipboard-list', x: 770, y: 30, layer: 1, status: 'dormant', description: 'Third-party risk tasks from ProcessUnity and SailPoint.' },
      { id: 'helpbot-calendar', label: 'My Day', type: 'helpbot', icon: 'calendar', x: 950, y: 30, layer: 1, status: 'dormant', description: 'Calendar view aggregated from M365 Graph and Oracle.' },

      // Layer 2 — NeMo Orchestrator (y: 230, 400)
      { id: 'nat-serve', label: 'nat serve', type: 'orchestrator', icon: 'server', x: 50, y: 230, layer: 2, status: 'dormant', description: 'NeMo Agent Toolkit long-lived HTTP service (nat serve --config_file config.yml --port 8001). Exposes all workflows as REST endpoints.' },
      { id: 'state-store', label: 'Session State', type: 'orchestrator', icon: 'database', x: 50, y: 400, layer: 2, status: 'dormant', description: 'Robust session-state abstraction layer to pause and resume meta-workflows. Handles asynchronous step-up auth (OTP).' },
      { id: 'workflow-config', label: 'Workflow YAML', type: 'config', icon: 'file-code', x: 230, y: 230, layer: 2, status: 'dormant', description: 'Declarative YAML config listing functions, LLMs, embedders, and workflow type. Single source of truth for the meta-orchestrator.' },
      { id: 'observability', label: 'Observability', type: 'observability', icon: 'activity', x: 230, y: 400, layer: 2, status: 'dormant', description: 'OpenTelemetry + NeMo Profiler integration. Traces every LLM call, tool invocation, and agent delegation with latency and quality metrics.' },
      { id: 'react-agent', label: 'react_agent', type: 'orchestrator', icon: 'brain', x: 500, y: 400, layer: 2, status: 'dormant', description: 'NeMo react_agent workflow — the meta-orchestrator. Receives user intents, reasons over available tools, calls domain agents, and enforces governance.' },
      { id: 'intent-classify', label: 'Intent Classifier', type: 'classify', icon: 'share-2', x: 680, y: 230, layer: 2, status: 'dormant', description: 'LLM-based intent detection. Determines domain (IT, HR, Finance, Vendor Risk, Identity) and selects which NeMo functions/tools to invoke.' },
      { id: 'tool-select', label: 'Tool Selector', type: 'route', icon: 'git-branch', x: 680, y: 400, layer: 2, status: 'dormant', description: 'Selects specific NeMo function(s) to call based on classified intent. Each function has a JSON schema and description controlling tool use.' },
      { id: 'approval-gate', label: 'Approval Gate', type: 'approval', icon: 'hand', x: 860, y: 230, layer: 2, status: 'dormant', description: 'Policy engine tags high-risk actions (e.g. sensitive access grants) and forces a Confirm step in the UI before NeMo executes the tool.' },
      { id: 'a2a-delegate', label: 'A2A Delegation', type: 'orchestrator', icon: 'arrow-right-left', x: 860, y: 400, layer: 2, status: 'dormant', description: 'Agent-to-Agent delegation. Meta-agent calls domain agent workflows as if they were tools.' },

      // Layer 3 — Domain Agents (y: 610)
      { id: 'domain-it', label: 'IT Agent', type: 'domain_agent', icon: 'monitor', x: 50, y: 610, layer: 3, status: 'dormant', description: 'NeMo workflow for IT operations. Tools: ServiceNow ITSM, M365 admin, Atlassian Jira.' },
      { id: 'domain-hr', label: 'HR Agent', type: 'domain_agent', icon: 'users', x: 280, y: 610, layer: 3, status: 'dormant', description: 'NeMo workflow for HR operations. Tools: ServiceNow HR, M365 People.' },
      { id: 'domain-finance', label: 'Finance Agent', type: 'domain_agent', icon: 'dollar-sign', x: 510, y: 610, layer: 3, status: 'dormant', description: 'NeMo workflow for Finance. Tools: Oracle Expenses REST API.' },
      { id: 'domain-vendor', label: 'Vendor Risk Agent', type: 'domain_agent', icon: 'shield-alert', x: 740, y: 610, layer: 3, status: 'dormant', description: 'NeMo workflow for third-party risk. Tools: ProcessUnity API, SailPoint API.' },
      { id: 'domain-identity', label: 'Identity Agent', type: 'domain_agent', icon: 'fingerprint', x: 970, y: 610, layer: 3, status: 'dormant', description: 'NeMo workflow for identity security. Tools: SailPoint SCIM/REST, Harbor Pilot.' },

      // Platform nodes — Row 1 (y: 790)
      { id: 'snow-nowassist', label: 'Now Assist', type: 'native_agent', icon: 'bot', x: 0, y: 790, layer: 3, status: 'dormant', description: 'ServiceNow Now Assist — native AI agent. NeMo tool servicenow_now_assist calls the Virtual Agent entrypoint for ITSM generative skills.' },
      { id: 'snow-rest', label: 'SN REST API', type: 'api_call', icon: 'globe', x: 140, y: 790, layer: 3, status: 'dormant', description: 'ServiceNow REST Table API (/api/now/table/incident). NeMo HTTP tool for explicit operations.' },
      { id: 'sf-agentforce', label: 'Agentforce', type: 'native_agent', icon: 'bot', x: 280, y: 790, layer: 3, status: 'dormant', description: 'Salesforce Agentforce — native AI agent for CRM triage and case resolution via Atlas Reasoning Engine.' },
      { id: 'sf-rest', label: 'SF REST/SOQL', type: 'api_call', icon: 'globe', x: 420, y: 790, layer: 3, status: 'dormant', description: 'Salesforce REST and SOQL APIs for direct CRM data access.' },
      { id: 'm365-copilot', label: 'M365 Copilot', type: 'native_agent', icon: 'bot', x: 560, y: 790, layer: 3, status: 'dormant', description: 'Microsoft 365 Copilot — the meta-orchestrator can be exposed as a Copilot plugin.' },
      { id: 'm365-graph', label: 'Graph API', type: 'api_call', icon: 'globe', x: 700, y: 790, layer: 3, status: 'dormant', description: 'Microsoft Graph REST endpoints for emails, calendar, Teams, files.' },
      { id: 'pu-ai', label: 'PU Evidence AI', type: 'native_agent', icon: 'bot', x: 840, y: 790, layer: 3, status: 'dormant', description: 'ProcessUnity Evidence Evaluator and Predictive Analytics for vendor risk assessment.' },
      { id: 'pu-rest', label: 'ProcessUnity API', type: 'api_call', icon: 'globe', x: 980, y: 790, layer: 3, status: 'dormant', description: 'ProcessUnity TPRM API. NeMo tool processunity_get_vendor_risk returns normalized risk summaries.' },
      { id: 'sailpoint-harbor', label: 'Harbor Pilot', type: 'native_agent', icon: 'bot', x: 1120, y: 790, layer: 3, status: 'dormant', description: 'SailPoint Harbor Pilot — AI agent for exploring identity data and building workflows.' },
      { id: 'sailpoint-rest', label: 'SailPoint API', type: 'api_call', icon: 'globe', x: 1260, y: 790, layer: 3, status: 'dormant', description: 'SailPoint REST and SCIM APIs for cross-system identity provisioning.' },

      // Platform nodes — Row 2 (y: 960)
      { id: 'atl-intelligence', label: 'Atlassian Intel', type: 'native_agent', icon: 'bot', x: 0, y: 960, layer: 3, status: 'dormant', description: 'Atlassian Intelligence — embedded AI for Jira/Confluence generation and summarization.' },
      { id: 'atl-rest', label: 'Jira/Confluence', type: 'api_call', icon: 'globe', x: 140, y: 960, layer: 3, status: 'dormant', description: 'Atlassian REST APIs for Jira issues and Confluence pages.' },
      { id: 'oracle-expense', label: 'Expense Asst', type: 'native_agent', icon: 'bot', x: 560, y: 960, layer: 3, status: 'dormant', description: 'Oracle Fusion Expense Assistant — conversational skill within FA Digital Assistant.' },
      { id: 'oracle-rest', label: 'Oracle Expenses', type: 'api_call', icon: 'globe', x: 700, y: 960, layer: 3, status: 'dormant', description: 'Oracle Fusion Expenses REST APIs. Step-up auth (OTP) requires session-state abstraction.' },

      // Layer 4 — Data & Models (y: 1180, 1350)
      { id: 'vectordb', label: 'Vector DB', type: 'vectordb', icon: 'database', x: 140, y: 1180, layer: 4, status: 'dormant', description: 'Enterprise vector store with curated embeddings. Transactional data, content data, and agent-generated content.' },
      { id: 'rag-tool', label: 'RAG Search', type: 'retrieval', icon: 'search', x: 350, y: 1180, layer: 4, status: 'dormant', description: 'NeMo RAG function — runs vector similarity search and returns relevant passages to orchestrator workflows.' },
      { id: 'llm-orchestration', label: 'Orchestration LLM', type: 'llm', icon: 'cpu', x: 560, y: 1180, layer: 4, status: 'dormant', description: 'Primary LLM used by the react_agent for reasoning, intent classification, and tool selection. Hosted via NeMo Microservices / NIM.' },
      { id: 'llm-summarize', label: 'Summarization LLM', type: 'llm', icon: 'cpu', x: 770, y: 1180, layer: 4, status: 'dormant', description: 'Secondary LLM for response summarization and cross-platform data synthesis.' },
      { id: 'embedder', label: 'Embedder', type: 'embedder', icon: 'zap', x: 350, y: 1350, layer: 4, status: 'dormant', description: 'NIM-hosted embedding model. Generates vectors for RAG indexing and query encoding.' },
      { id: 'nim-services', label: 'NeMo Microservices', type: 'nim', icon: 'layers', x: 560, y: 1350, layer: 4, status: 'dormant', description: 'NeMo Microservices / NIM runtime hosting LLMs and embedders.' },
      { id: 'tool-registry', label: 'Tool Registry', type: 'registry', icon: 'package', x: 980, y: 1180, layer: 4, status: 'dormant', description: 'Central registry of all NeMo functions (tools). Connectors are promoted here after AI-assisted onboarding passes nat eval testing.' },
    ],
    connections: [
      // Layer 1 → Layer 2
      { from: 'helpbot-chat', to: 'nat-serve' },

      // Within Layer 2
      { from: 'nat-serve', to: 'workflow-config' },
      { from: 'nat-serve', to: 'react-agent' },
      { from: 'nat-serve', to: 'state-store' },
      { from: 'react-agent', to: 'intent-classify' },
      { from: 'intent-classify', to: 'tool-select' },
      { from: 'tool-select', to: 'a2a-delegate' },
      { from: 'tool-select', to: 'approval-gate' },
      { from: 'approval-gate', to: 'a2a-delegate' },
      { from: 'react-agent', to: 'observability' },

      // Layer 2 → Layer 3 (A2A delegation)
      { from: 'a2a-delegate', to: 'domain-it' },
      { from: 'a2a-delegate', to: 'domain-hr' },
      { from: 'a2a-delegate', to: 'domain-finance' },
      { from: 'a2a-delegate', to: 'domain-vendor' },
      { from: 'a2a-delegate', to: 'domain-identity' },

      // Domain agents → Platform tools
      { from: 'domain-it', to: 'snow-nowassist' },
      { from: 'domain-it', to: 'snow-rest' },
      { from: 'domain-it', to: 'atl-intelligence' },
      { from: 'domain-it', to: 'atl-rest' },
      { from: 'domain-it', to: 'm365-copilot' },
      { from: 'domain-it', to: 'm365-graph' },
      { from: 'domain-hr', to: 'sf-agentforce' },
      { from: 'domain-hr', to: 'sf-rest' },
      { from: 'domain-finance', to: 'oracle-expense' },
      { from: 'domain-finance', to: 'oracle-rest' },
      { from: 'domain-vendor', to: 'pu-ai' },
      { from: 'domain-vendor', to: 'pu-rest' },
      { from: 'domain-identity', to: 'sailpoint-harbor' },
      { from: 'domain-identity', to: 'sailpoint-rest' },

      // Layer 2/3 → Layer 4 (data and model calls)
      { from: 'react-agent', to: 'llm-orchestration' },
      { from: 'react-agent', to: 'rag-tool' },
      { from: 'rag-tool', to: 'vectordb' },
      { from: 'rag-tool', to: 'embedder' },
      { from: 'llm-orchestration', to: 'nim-services' },
      { from: 'llm-summarize', to: 'nim-services' },
      { from: 'embedder', to: 'nim-services' },

      // Tool registry read path
      { from: 'tool-select', to: 'tool-registry' },

      // Response path
      { from: 'react-agent', to: 'llm-summarize' },
      { from: 'nat-serve', to: 'helpbot-chat' },
    ],
    scenarios: [
      // Scenario 1: IT Incident + Jira Cross-Platform Lookup
      {
        id: 'it-incident-jira',
        name: 'IT Incident + Jira Lookup',
        description: 'Cross-platform query: find open ServiceNow incidents and related Jira tickets',
        query: 'Show me my open incidents and related Jira tickets',
        activeNodes: [
          'helpbot-chat', 'nat-serve', 'workflow-config', 'react-agent', 'intent-classify',
          'tool-select', 'a2a-delegate', 'domain-it', 'snow-rest', 'atl-rest',
          'llm-orchestration', 'rag-tool', 'vectordb', 'embedder', 'nim-services',
          'llm-summarize', 'observability', 'state-store', 'tool-registry',
        ],
        chosenPath: ['domain-it'],
        events: [
          { id: 'e1', message: '`nat serve` received POST /chat', timing: 0, status: 'completed', nodeIds: ['helpbot-chat', 'nat-serve'] },
          { id: 'e2', message: 'Loaded workflow config: meta_orchestrator.yml', timing: 50, status: 'completed', nodeIds: ['workflow-config'] },
          { id: 'e3', message: '`react_agent` workflow started', timing: 80, status: 'completed', nodeIds: ['react-agent'] },
          { id: 'e4', message: 'LLM orchestration call for intent classification (620ms)', timing: 100, status: 'running', nodeIds: ['react-agent', 'llm-orchestration'] },
          { id: 'e5', message: 'Intent classified: IT / cross-platform lookup', timing: 720, status: 'completed', nodeIds: ['intent-classify'] },
          { id: 'e6', message: 'Selected tools: `servicenow_rest_get_incidents`, `jira_rest_search`', timing: 780, status: 'completed', nodeIds: ['tool-select'] },
          { id: 'e6b', message: '`nat eval` running synthetic tests on connectors…', timing: 790, status: 'running', nodeIds: ['tool-registry'] },
          { id: 'e6c', message: 'Connector passed 12/12 synthetic tests', timing: 810, status: 'completed', nodeIds: ['tool-registry'] },
          { id: 'e7', message: 'Delegating to `domain-it` agent (NeMo A2A)', timing: 820, status: 'completed', nodeIds: ['a2a-delegate', 'domain-it'] },
          { id: 'e8', message: 'GET `/api/now/table/incident?sysparm_query=active=true` → 200 OK (142ms)', timing: 850, status: 'running', nodeIds: ['snow-rest'] },
          { id: 'e9', message: 'ServiceNow: 3 active incidents found', timing: 992, status: 'completed', nodeIds: ['snow-rest'] },
          { id: 'e10', message: 'GET `/rest/api/3/search?jql=assignee=currentUser()` → 200 OK (89ms)', timing: 1000, status: 'running', nodeIds: ['atl-rest'] },
          { id: 'e11', message: 'Jira: 5 open tickets found', timing: 1089, status: 'completed', nodeIds: ['atl-rest'] },
          { id: 'e12', message: 'Vector search: 4 relevant KB articles retrieved (32ms)', timing: 1100, status: 'completed', nodeIds: ['rag-tool', 'vectordb', 'embedder'] },
          { id: 'e13', message: 'OpenTelemetry span: `tool.servicenow_rest` 142ms, `tool.jira_rest` 89ms', timing: 1150, status: 'completed', nodeIds: ['observability'] },
          { id: 'e14', message: 'Summarization LLM call — generating cross-platform summary (620ms)', timing: 1200, status: 'running', nodeIds: ['llm-summarize', 'nim-services'] },
          { id: 'e15', message: 'Summary generated', timing: 1820, status: 'completed', nodeIds: ['llm-summarize'] },
          { id: 'e16', message: 'Response delivered to HelpBot', timing: 1850, status: 'completed', nodeIds: ['nat-serve', 'helpbot-chat'] },
        ],
        chatMessages: [
          { role: 'user', content: 'Show me my open incidents and related Jira tickets', timing: 0 },
          { role: 'system', content: 'Intent classified: IT / cross-platform lookup', timing: 720 },
          { role: 'system', content: 'Tools selected: `servicenow_rest_get_incidents`, `jira_rest_search`', timing: 780 },
          { role: 'system', content: '`nat eval` — Connector passed 12/12 synthetic tests ✓', timing: 810 },
          { role: 'system', content: 'Delegating to IT Agent (NeMo A2A)', timing: 820 },
          { role: 'system', content: 'ServiceNow: 3 active incidents found (142ms)', timing: 992 },
          { role: 'system', content: 'Jira: 5 open tickets found (89ms)', timing: 1089 },
          { role: 'system', content: 'RAG: 4 relevant KB articles retrieved', timing: 1100 },
          { role: 'system', content: 'Generating cross-platform summary…', timing: 1200 },
          { role: 'assistant', content: 'You have **3 open ServiceNow incidents** and **5 Jira tickets**:\n\n**ServiceNow:**\n• INC001234 — VPN connectivity failure (P2, assigned to you)\n• INC001267 — Email sync issue (P3)\n• INC001289 — Laptop refresh request (P4)\n\n**Related Jira Tickets:**\n• JIRA-567 — "Investigate VPN gateway timeout" (linked to INC001234)\n• JIRA-582 — "O365 connector config update"\n• JIRA-590 — "Hardware procurement automation"\n• JIRA-601 — "SSO login failure triage"\n• JIRA-612 — "Network monitoring dashboard"\n\n*INC001234 is linked to JIRA-567 — both relate to the VPN gateway issue reported Tuesday.*', timing: 1850 },
        ],
      },
      // Scenario 2: Vendor Risk with Approval Gate
      {
        id: 'vendor-risk-approval',
        name: 'Vendor Risk + Approval Gate',
        description: 'High-risk vendor access request triggering human-in-the-loop approval',
        query: 'Grant admin access to the ProcessUnity staging environment for vendor onboarding',
        activeNodes: [
          'helpbot-chat', 'nat-serve', 'workflow-config', 'react-agent', 'intent-classify',
          'tool-select', 'approval-gate', 'a2a-delegate', 'domain-vendor', 'domain-identity',
          'pu-rest', 'pu-ai', 'sailpoint-rest',
          'llm-orchestration', 'llm-summarize', 'nim-services',
          'observability', 'state-store', 'helpbot-approvals',
        ],
        chosenPath: ['domain-vendor', 'domain-identity'],
        events: [
          { id: 'e1', message: '`nat serve` received POST /chat', timing: 0, status: 'completed', nodeIds: ['helpbot-chat', 'nat-serve'] },
          { id: 'e2', message: 'Loaded workflow config: meta_orchestrator.yml', timing: 50, status: 'completed', nodeIds: ['workflow-config'] },
          { id: 'e3', message: '`react_agent` workflow started', timing: 80, status: 'completed', nodeIds: ['react-agent'] },
          { id: 'e4', message: 'LLM orchestration call for intent classification (580ms)', timing: 100, status: 'running', nodeIds: ['react-agent', 'llm-orchestration'] },
          { id: 'e5', message: 'Intent classified: Vendor Risk / access_grant', timing: 680, status: 'completed', nodeIds: ['intent-classify'] },
          { id: 'e6', message: 'Selected tools: `processunity_get_vendor_risk`, `sailpoint_provision_access`', timing: 730, status: 'completed', nodeIds: ['tool-select'] },
          { id: 'e7', message: '⚠️ High-risk action detected: `grant_admin_access`. Awaiting confirmation.', timing: 760, status: 'running', nodeIds: ['approval-gate'] },
          { id: 'e8', message: 'Approval request pushed to HelpBot Approvals panel', timing: 800, status: 'completed', nodeIds: ['helpbot-approvals'] },
          { id: 'e9', message: '✅ User confirmed. Proceeding with delegated execution.', timing: 2500, status: 'completed', nodeIds: ['approval-gate'] },
          { id: 'e10', message: 'Delegating to `domain-vendor` and `domain-identity` agents (NeMo A2A)', timing: 2550, status: 'completed', nodeIds: ['a2a-delegate', 'domain-vendor', 'domain-identity'] },
          { id: 'e11', message: 'ProcessUnity: vendor risk assessment in progress', timing: 2600, status: 'running', nodeIds: ['pu-rest', 'pu-ai'] },
          { id: 'e12', message: 'ProcessUnity: Vendor risk score 72/100 (Medium) — 3 open findings', timing: 2900, status: 'completed', nodeIds: ['pu-rest'] },
          { id: 'e12b', message: 'Step-up auth required: SailPoint MFA. Session paused.', timing: 2920, status: 'running', nodeIds: ['sailpoint-rest'] },
          { id: 'e13', message: 'SailPoint: provisioning admin access to staging environment', timing: 2950, status: 'running', nodeIds: ['sailpoint-rest'] },
          { id: 'e14', message: 'SailPoint: access provisioned with 30-day expiry, audit trail created', timing: 3200, status: 'completed', nodeIds: ['sailpoint-rest'] },
          { id: 'e15', message: 'OpenTelemetry span: `tool.processunity` 300ms, `tool.sailpoint` 250ms', timing: 3250, status: 'completed', nodeIds: ['observability'] },
          { id: 'e16', message: 'Summarization LLM call — composing final response (450ms)', timing: 3300, status: 'running', nodeIds: ['llm-summarize', 'nim-services'] },
          { id: 'e17', message: 'Response delivered to HelpBot', timing: 3750, status: 'completed', nodeIds: ['nat-serve', 'helpbot-chat'] },
        ],
        chatMessages: [
          { role: 'user', content: 'Grant admin access to the ProcessUnity staging environment for vendor onboarding', timing: 0 },
          { role: 'system', content: 'Intent classified: Vendor Risk / access_grant', timing: 680 },
          { role: 'system', content: 'Tools selected: `processunity_get_vendor_risk`, `sailpoint_provision_access`', timing: 730 },
          { role: 'system', content: '⚠️ Approval required: grant_admin_access to ProcessUnity staging. This is a high-risk action.', timing: 760 },
          { role: 'system', content: '✅ User confirmed. Proceeding.', timing: 2500 },
          { role: 'system', content: 'Delegating to Vendor Risk + Identity agents', timing: 2550 },
          { role: 'system', content: 'ProcessUnity: Risk score 72/100 (Medium) — 3 open findings', timing: 2900 },
          { role: 'system', content: '🔒 Step-up auth required: SailPoint MFA. Session paused.', timing: 2920 },
          { role: 'system', content: 'SailPoint: Admin access provisioned (30-day expiry)', timing: 3200 },
          { role: 'assistant', content: '**Access Granted** ✅\n\nAdmin access to the ProcessUnity staging environment has been provisioned:\n\n**Vendor Risk Assessment:**\n• Risk Score: 72/100 (Medium)\n• Open Findings: 3 (2 low, 1 medium)\n• Last Assessment: 2025-12-15\n• Recommendation: Proceed with monitoring\n\n**Access Details:**\n• Role: Admin (staging only)\n• Expiry: 30 days (auto-revoke Mar 21, 2026)\n• Audit Trail: Created in SailPoint\n• MFA: Required for all sessions\n\n**Next Steps:**\n• Review open findings in ProcessUnity dashboard\n• Complete vendor onboarding checklist\n• Schedule security review before production access\n\n*Approval logged. Audit reference: APR-2026-0219-001*', timing: 3750 },
        ],
      },
    ],
  },
];

export function getBlueprintById(id: string): Blueprint | undefined {
  return blueprints.find(bp => bp.id === id);
}

export function getScenarioById(blueprintId: string, scenarioId: string) {
  const blueprint = getBlueprintById(blueprintId);
  return blueprint?.scenarios.find(s => s.id === scenarioId);
}

