import { ConnectorCard, OnboardingStep, PayloadInspection } from './types';

export const connectors: ConnectorCard[] = [
  {
    id: 'snow-itsm',
    name: 'ServiceNow ITSM Connector',
    platform: 'ServiceNow',
    icon: 'globe',
    version: '1.2.0',
    domain: 'IT',
    capability: 'full',
    status: 'healthy',
    intents: ['incident_lookup', 'incident_create', 'approval_check'],
    tools: [
      {
        name: 'servicenow_rest_get_incidents',
        method: 'GET',
        endpoint: '/api/now/table/incident',
        inputSchema: { query: 'string', limit: 'number?' },
        outputSchema: { incidents: 'Incident[]' },
      },
      {
        name: 'servicenow_now_assist',
        method: 'POST',
        endpoint: '/virtual_agent/invoke',
        inputSchema: { utterance: 'string' },
        outputSchema: { response: 'string' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (normalized results)',
      delegateAgent: 'Now Assist Virtual Agent',
    },
    mcpMapping: {
      toolName: 'servicenow.incidents.list',
      resourceUri: 'servicenow://incidents',
    },
    lastUsed: '2 min ago',
    callsToday: 847,
  },
  {
    id: 'sf-crm',
    name: 'Salesforce CRM Connector',
    platform: 'Salesforce',
    icon: 'globe',
    version: '2.0.1',
    domain: 'HR',
    capability: 'full',
    status: 'healthy',
    intents: ['case_lookup', 'case_create', 'crm_triage'],
    tools: [
      {
        name: 'salesforce_rest_query',
        method: 'GET',
        endpoint: '/services/data/v59.0/query',
        inputSchema: { soql: 'string' },
        outputSchema: { records: 'SObject[]', totalSize: 'number' },
      },
      {
        name: 'salesforce_agentforce_invoke',
        method: 'POST',
        endpoint: '/agentforce/api/invoke',
        inputSchema: { utterance: 'string', context: 'object?' },
        outputSchema: { response: 'string', actions: 'Action[]?' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (normalized results)',
      delegateAgent: 'Agentforce Atlas Reasoning Engine',
    },
    mcpMapping: {
      toolName: 'salesforce.cases.query',
      resourceUri: 'salesforce://cases',
    },
    lastUsed: '5 min ago',
    callsToday: 412,
  },
  {
    id: 'atl-jira',
    name: 'Atlassian Jira Connector',
    platform: 'Atlassian',
    icon: 'globe',
    version: '1.4.2',
    domain: 'IT',
    capability: 'full',
    status: 'healthy',
    intents: ['issue_search', 'issue_create', 'confluence_search'],
    tools: [
      {
        name: 'jira_rest_search',
        method: 'GET',
        endpoint: '/rest/api/3/search',
        inputSchema: { jql: 'string', maxResults: 'number?' },
        outputSchema: { issues: 'Issue[]', total: 'number' },
      },
      {
        name: 'confluence_rest_search',
        method: 'GET',
        endpoint: '/wiki/rest/api/content/search',
        inputSchema: { cql: 'string', limit: 'number?' },
        outputSchema: { results: 'Content[]' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (normalized results)',
      delegateAgent: 'Atlassian Intelligence (UX-only)',
    },
    mcpMapping: {
      toolName: 'atlassian.issues.search',
      resourceUri: 'atlassian://jira/issues',
    },
    lastUsed: '1 min ago',
    callsToday: 623,
  },
  {
    id: 'm365-graph',
    name: 'Microsoft Graph Connector',
    platform: 'Microsoft',
    icon: 'globe',
    version: '3.1.0',
    domain: 'IT',
    capability: 'full',
    status: 'healthy',
    intents: ['email_search', 'calendar_read', 'teams_message'],
    tools: [
      {
        name: 'm365_graph_mail',
        method: 'GET',
        endpoint: '/v1.0/me/messages',
        inputSchema: { filter: 'string?', top: 'number?' },
        outputSchema: { value: 'Message[]' },
      },
      {
        name: 'm365_graph_calendar',
        method: 'GET',
        endpoint: '/v1.0/me/calendarview',
        inputSchema: { startDateTime: 'string', endDateTime: 'string' },
        outputSchema: { value: 'Event[]' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (normalized results)',
      delegateAgent: 'M365 Copilot (bidirectional plugin)',
    },
    mcpMapping: {
      toolName: 'microsoft.graph.mail',
      resourceUri: 'microsoft://graph/me/messages',
    },
    lastUsed: '30 sec ago',
    callsToday: 1205,
  },
  {
    id: 'oracle-expenses',
    name: 'Oracle Expenses Connector',
    platform: 'Oracle',
    icon: 'globe',
    version: '1.0.3',
    domain: 'Finance',
    capability: 'full',
    status: 'healthy',
    intents: ['expense_create', 'expense_check', 'expense_modify'],
    tools: [
      {
        name: 'oracle_expenses_list',
        method: 'GET',
        endpoint: '/fscmRestApi/resources/11.13.18.05/expenseReports',
        inputSchema: { filter: 'string?', limit: 'number?' },
        outputSchema: { items: 'ExpenseReport[]', count: 'number' },
      },
      {
        name: 'oracle_expenses_create',
        method: 'POST',
        endpoint: '/fscmRestApi/resources/11.13.18.05/expenseReports',
        inputSchema: { purpose: 'string', amount: 'number', currency: 'string' },
        outputSchema: { reportId: 'string', status: 'string' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (step-up OTP auth)',
      delegateAgent: 'Oracle Fusion Expense Assistant',
    },
    mcpMapping: {
      toolName: 'oracle.expenses.list',
      resourceUri: 'oracle://fusion/expenses',
    },
    lastUsed: '12 min ago',
    callsToday: 89,
  },
  {
    id: 'pu-tprm',
    name: 'ProcessUnity TPRM Connector',
    platform: 'ProcessUnity',
    icon: 'globe',
    version: '1.1.0',
    domain: 'Vendor Risk',
    capability: 'full',
    status: 'healthy',
    intents: ['vendor_risk_lookup', 'evidence_evaluate'],
    tools: [
      {
        name: 'processunity_get_vendor_risk',
        method: 'GET',
        endpoint: '/api/v2/vendors/risk-summary',
        inputSchema: { vendorId: 'string?' },
        outputSchema: { riskScore: 'number', findings: 'Finding[]' },
      },
      {
        name: 'processunity_evidence_eval',
        method: 'POST',
        endpoint: '/api/v2/evidence/evaluate',
        inputSchema: { documentId: 'string', assessmentType: 'string' },
        outputSchema: { score: 'number', summary: 'string' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (normalized results)',
      delegateAgent: 'PU Evidence Evaluator AI',
    },
    mcpMapping: {
      toolName: 'processunity.vendors.risk',
      resourceUri: 'processunity://vendors/risk',
    },
    lastUsed: '8 min ago',
    callsToday: 156,
  },
  {
    id: 'sp-identity',
    name: 'SailPoint Identity Connector',
    platform: 'SailPoint',
    icon: 'globe',
    version: '2.3.0',
    domain: 'Identity',
    capability: 'full',
    status: 'healthy',
    intents: ['access_provision', 'access_review', 'identity_lookup'],
    tools: [
      {
        name: 'sailpoint_provision_access',
        method: 'POST',
        endpoint: '/v3/access-requests',
        inputSchema: { identityId: 'string', accessProfileId: 'string', justification: 'string' },
        outputSchema: { requestId: 'string', status: 'string', expiry: 'string' },
      },
      {
        name: 'sailpoint_search_identities',
        method: 'GET',
        endpoint: '/v3/search/identities',
        inputSchema: { query: 'string', limit: 'number?' },
        outputSchema: { identities: 'Identity[]', count: 'number' },
      },
    ],
    runtime: {
      invoke: 'HTTP handler (SCIM/REST)',
      delegateAgent: 'Harbor Pilot (in-product)',
    },
    mcpMapping: {
      toolName: 'sailpoint.access.provision',
      resourceUri: 'sailpoint://identities',
    },
    lastUsed: '4 min ago',
    callsToday: 298,
  },
];

export const onboardingSteps: OnboardingStep[] = [
  {
    id: 'onboard-analyze',
    label: 'API Analysis',
    icon: 'search',
    description: 'NeMo workflow ingests OpenAPI spec, clusters endpoints, queries platform metadata APIs for tenant-specific custom fields.',
    status: 'dormant',
  },
  {
    id: 'onboard-schema',
    label: 'Schema Gen',
    icon: 'file-code',
    description: 'Agent writes candidate JSON schemas for inputs/outputs aligned with NeMo functions format and MCP tool schemas.',
    status: 'dormant',
  },
  {
    id: 'onboard-config',
    label: 'Config Synthesis',
    icon: 'settings',
    description: 'Drafts YAML fragment: base URLs, HTTP methods, auth structures for NeMo config.',
    status: 'dormant',
  },
  {
    id: 'onboard-review',
    label: 'Human Review',
    icon: 'hand',
    description: 'Platform owner reviews generated config. nat eval runs synthetic tests to validate connector.',
    status: 'dormant',
  },
  {
    id: 'onboard-promote',
    label: 'Promote to Registry',
    icon: 'package',
    description: 'Approved connector enters the Tool Registry for meta-orchestrator consumption.',
    status: 'dormant',
  },
];

export const payloadSamples: Record<string, PayloadInspection> = {
  'snow-rest': {
    nodeId: 'snow-rest',
    toolName: 'servicenow_rest_get_incidents',
    inputJson: {
      method: 'GET',
      url: '/api/now/table/incident',
      params: { sysparm_query: 'active=true', sysparm_limit: 10 },
      headers: { Authorization: 'Bearer ****', Accept: 'application/json' },
    },
    outputJson: {
      status: 200,
      incidents: [
        { number: 'INC001234', short_description: 'VPN connectivity failure', priority: 'P2', state: 'In Progress' },
        { number: 'INC001267', short_description: 'Email sync issue', priority: 'P3', state: 'New' },
        { number: 'INC001289', short_description: 'Laptop refresh request', priority: 'P4', state: 'New' },
      ],
    },
    schema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'ServiceNow encoded query string' },
        limit: { type: 'number', description: 'Max results to return' },
      },
      required: ['query'],
    },
    mcpTool: 'servicenow.incidents.list',
    mcpResource: 'servicenow://incidents',
  },
  'atl-rest': {
    nodeId: 'atl-rest',
    toolName: 'jira_rest_search',
    inputJson: {
      method: 'GET',
      url: '/rest/api/3/search',
      params: { jql: 'assignee=currentUser() AND status!=Done', maxResults: 20 },
      headers: { Authorization: 'Basic ****', Accept: 'application/json' },
    },
    outputJson: {
      status: 200,
      total: 5,
      issues: [
        { key: 'JIRA-567', summary: 'Investigate VPN gateway timeout', status: 'In Progress' },
        { key: 'JIRA-582', summary: 'O365 connector config update', status: 'Open' },
        { key: 'JIRA-590', summary: 'Hardware procurement automation', status: 'Open' },
        { key: 'JIRA-601', summary: 'SSO login failure triage', status: 'In Review' },
        { key: 'JIRA-612', summary: 'Network monitoring dashboard', status: 'Open' },
      ],
    },
    schema: {
      type: 'object',
      properties: {
        jql: { type: 'string', description: 'JQL query string' },
        maxResults: { type: 'number', description: 'Max issues to return' },
      },
      required: ['jql'],
    },
    mcpTool: 'atlassian.issues.search',
    mcpResource: 'atlassian://jira/issues',
  },
  'pu-rest': {
    nodeId: 'pu-rest',
    toolName: 'processunity_get_vendor_risk',
    inputJson: {
      method: 'GET',
      url: '/api/v2/vendors/risk-summary',
      params: { vendorId: 'pu-staging-001' },
      headers: { Authorization: 'Bearer ****', Accept: 'application/json' },
    },
    outputJson: {
      status: 200,
      riskScore: 72,
      riskLevel: 'Medium',
      findings: [
        { id: 'F-101', severity: 'low', description: 'Missing SOC2 renewal' },
        { id: 'F-102', severity: 'low', description: 'Incomplete data processing agreement' },
        { id: 'F-103', severity: 'medium', description: 'Third-party sub-processor not disclosed' },
      ],
      lastAssessment: '2025-12-15',
    },
    schema: {
      type: 'object',
      properties: {
        vendorId: { type: 'string', description: 'ProcessUnity vendor identifier' },
      },
    },
    mcpTool: 'processunity.vendors.risk',
    mcpResource: 'processunity://vendors/risk',
  },
  'sailpoint-rest': {
    nodeId: 'sailpoint-rest',
    toolName: 'sailpoint_provision_access',
    inputJson: {
      method: 'POST',
      url: '/v3/access-requests',
      body: {
        identityId: 'usr-vendor-onboard-01',
        accessProfileId: 'ap-admin-staging',
        justification: 'Vendor onboarding — admin access to ProcessUnity staging',
        expiryDays: 30,
      },
      headers: { Authorization: 'Bearer ****', 'Content-Type': 'application/json' },
    },
    outputJson: {
      status: 201,
      requestId: 'REQ-2026-0219-001',
      accessGranted: true,
      expiry: '2026-03-21T00:00:00Z',
      auditTrailId: 'AUD-2026-0219-001',
      mfaRequired: true,
    },
    schema: {
      type: 'object',
      properties: {
        identityId: { type: 'string' },
        accessProfileId: { type: 'string' },
        justification: { type: 'string' },
        expiryDays: { type: 'number' },
      },
      required: ['identityId', 'accessProfileId', 'justification'],
    },
    mcpTool: 'sailpoint.access.provision',
    mcpResource: 'sailpoint://identities',
  },
  'pu-ai': {
    nodeId: 'pu-ai',
    toolName: 'processunity_evidence_eval',
    inputJson: {
      method: 'POST',
      url: '/api/v2/evidence/evaluate',
      body: { documentId: 'doc-soc2-2025', assessmentType: 'annual_review' },
      headers: { Authorization: 'Bearer ****', 'Content-Type': 'application/json' },
    },
    outputJson: {
      status: 200,
      score: 72,
      summary: 'SOC2 Type II report reviewed. 3 findings identified, 2 low severity, 1 medium severity.',
      recommendation: 'Proceed with monitoring',
    },
    schema: {
      type: 'object',
      properties: {
        documentId: { type: 'string' },
        assessmentType: { type: 'string', enum: ['annual_review', 'initial_assessment', 'incident_review'] },
      },
      required: ['documentId', 'assessmentType'],
    },
  },
  'snow-nowassist': {
    nodeId: 'snow-nowassist',
    toolName: 'servicenow_now_assist',
    inputJson: {
      method: 'POST',
      url: '/virtual_agent/invoke',
      body: { utterance: 'Show my open incidents' },
      headers: { Authorization: 'Bearer ****', 'Content-Type': 'application/json' },
    },
    outputJson: {
      status: 200,
      response: 'You have 3 active incidents. The highest priority is INC001234 — VPN connectivity failure (P2).',
      suggestedActions: ['View INC001234', 'Escalate to network team', 'Create follow-up'],
    },
    schema: {
      type: 'object',
      properties: {
        utterance: { type: 'string', description: 'Natural language query to Virtual Agent' },
      },
      required: ['utterance'],
    },
    mcpTool: 'servicenow.nowassist.invoke',
    mcpResource: 'servicenow://virtual-agent',
  },
};
